In [3]:
import numpy as np

In [16]:
a = np.arange(15) #single dimensional
print(a)
a = np.arange(15).reshape(3,5) # multi dimensional
a

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
# size of array
a.size

15

In [7]:
# dimension in array
a.ndim

2

In [17]:
# datatype of array
a.dtype

dtype('int32')

In [36]:
list_b = [1,2,3,4,5,6,7,8,9]

b = np.array(list_b).reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
# creating multi_dimension array from a iterator
b = np.array([(1.5,2,3),(4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [38]:
# dtype can also be specified
c = np.array( [ [1,2], [3,4]],dtype = complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [39]:
# array of zeros
zeros = np.zeros( (3,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [40]:
# array of onces
ones = np.ones( (2,3,4), dtype = np.int16)
ones

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [41]:
# custom range
cd = np.arange(0,2,0.3)
cd

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [43]:
# getting the required number of elements
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [45]:
a = np.array( [20,30,40,50] )

b = np.arange(4) #array ([0,1,2,3])

c = a-b
c

array([20, 29, 38, 47])

In [46]:
b**2 # output : array([0,1,4,9])

10*np.sin(a) # output : array([9.12945251, -9.88031624,7.4511316,-2.62374854])

a<35

array([ True,  True, False, False])

In [50]:
A = np.array( [[1,1], [0,1]])
B = np.array( [[2,0], [3,4]])

prod1 = A * B
prod2 = A @ B

prod3 = A.dot(B)
prod3

array([[5, 4],
       [3, 4]])

In [67]:
a = np.ones((2,3),dtype = int)
b = np.random.random((2,3))
a*= 3
b+= a
b

array([[3.02575071, 3.1416092 , 3.05041138],
       [3.92173805, 3.02227761, 3.83358504]])

In [56]:
a = np.random.random((2,3))

In [57]:
a.sum()

3.4083636815251395

In [58]:
a.min()

0.08185759735434117

In [60]:
a.max()

0.8238558642083338

In [61]:
b

array([[3.02194904, 3.41642322, 3.18047697],
       [3.11947393, 3.29500349, 3.84117551]])

In [63]:
b[0:5,1]

array([3.41642322, 3.29500349])

In [64]:
b[ : ,1]

array([3.41642322, 3.29500349])

In [68]:
b[1:3, :]

array([[3.92173805, 3.02227761, 3.83358504]])

In [70]:
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))

In [71]:
np.vstack((a,b))

array([[8., 1.],
       [0., 8.],
       [8., 0.],
       [8., 3.]])

In [73]:
np.hstack((a,b))

array([[8., 1., 8., 0.],
       [0., 8., 8., 3.]])

In [78]:
a = np.floor(10*np.random.random((2,12)))

In [79]:
np.hsplit(a,3)

[array([[1., 1., 5., 0.],
        [1., 0., 0., 6.]]),
 array([[1., 0., 6., 0.],
        [7., 3., 1., 9.]]),
 array([[8., 0., 9., 9.],
        [0., 4., 3., 6.]])]

In [80]:
np.hsplit(a,(3,4))

[array([[1., 1., 5.],
        [1., 0., 0.]]),
 array([[0.],
        [6.]]),
 array([[1., 0., 6., 0., 8., 0., 9., 9.],
        [7., 3., 1., 9., 0., 4., 3., 6.]])]