In [4]:
import numpy as np

In [5]:
a = np.arange(15) #single dimensional
print(a)
a = np.arange(15).reshape(3,5) # multi dimensional
a

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
# size of array
a.size

15

In [7]:
# dimension in array
a.ndim

2

In [8]:
# datatype of array
a.dtype

dtype('int32')

In [9]:
list_b = [1,2,3,4,5,6,7,8,9]

b = np.array(list_b).reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
# creating multi_dimension array from a iterator
b = np.array([(1.5,2,3),(4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [11]:
# dtype can also be specified
c = np.array( [ [1,2], [3,4]],dtype = complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [12]:
# array of zeros
zeros = np.zeros( (3,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
# array of onces
ones = np.ones( (2,3,4), dtype = np.int16)
ones

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [14]:
# custom range
cd = np.arange(0,2,0.3)
cd

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [15]:
# getting the required number of elements
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [16]:
a = np.array( [20,30,40,50] )

b = np.arange(4) #array ([0,1,2,3])

c = a-b
c

array([20, 29, 38, 47])

In [17]:
b**2 # output : array([0,1,4,9])

10*np.sin(a) # output : array([9.12945251, -9.88031624,7.4511316,-2.62374854])

a<35

array([ True,  True, False, False])

In [18]:
A = np.array( [[1,1], [0,1]])
B = np.array( [[2,0], [3,4]])

prod1 = A * B
prod2 = A @ B

prod3 = A.dot(B)
prod3

array([[5, 4],
       [3, 4]])

In [19]:
a = np.ones((2,3),dtype = int)
b = np.random.random((2,3))
a*= 3
b+= a
b

array([[3.37138695, 3.15937191, 3.51009928],
       [3.87060806, 3.22159077, 3.0751764 ]])

In [20]:
a = np.random.random((2,3))

In [21]:
a.sum()

3.1369158388451583

In [22]:
a.min()

0.1559409115866338

In [23]:
a.max()

0.9918873280356225

In [24]:
b

array([[3.37138695, 3.15937191, 3.51009928],
       [3.87060806, 3.22159077, 3.0751764 ]])

In [25]:
b[0:5,1]

array([3.15937191, 3.22159077])

In [26]:
b[ : ,1]

array([3.15937191, 3.22159077])

In [27]:
b[1:3, :]

array([[3.87060806, 3.22159077, 3.0751764 ]])

In [28]:
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))

In [29]:
np.vstack((a,b))

array([[9., 8.],
       [0., 9.],
       [6., 4.],
       [9., 8.]])

In [30]:
np.hstack((a,b))

array([[9., 8., 6., 4.],
       [0., 9., 9., 8.]])

In [31]:
a = np.floor(10*np.random.random((2,12)))

In [32]:
np.hsplit(a,3)

[array([[5., 5., 0., 7.],
        [3., 4., 0., 0.]]),
 array([[6., 7., 2., 0.],
        [0., 1., 8., 7.]]),
 array([[8., 2., 3., 6.],
        [4., 1., 1., 1.]])]

In [33]:
np.hsplit(a,(3,4))

[array([[5., 5., 0.],
        [3., 4., 0.]]),
 array([[7.],
        [0.]]),
 array([[6., 7., 2., 0., 8., 2., 3., 6.],
        [0., 1., 8., 7., 4., 1., 1., 1.]])]